name: Build ThunderTools on Linux

on:
  push:
    # branches: ["master"]
  pull_request:
    branches: ["master"]
 
jobs:
  ThunderNanoServices:
    uses: rdkcentral/ThunderNanoServices/.github/workflows/Build ThunderNanoServices on Linux.yml@master

  ThunderNanoServicesRDK:
    uses: VeithMetro/ThunderNanoServicesRDK/.github/workflows/Build ThunderNanoServicesRDK on Linux.yml@master
